# Screen
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

# Grid
SQUARE_SIZE = 40
GRID_WIDTH = SCREEN_WIDTH // SQUARE_SIZE
GRID_HEIGHT = SCREEN_HEIGHT // SQUARE_SIZE
GRID_SIZE = GRID_WIDTH * GRID_HEIGHT

# Colors
FONT_COLOR = "#FFFFFF"
BG_COLOR = "#000000"
ALIVE_SNAKE_COLOR = "#00FF00"
DEAD_SNAKE_COLOR = "#960000"
FOOD_COLOR = "#FF0000"

# Game Over
MAX_NO_FOOD_MOVES = GRID_SIZE * 1.5
