# Grid
GRID_WIDTH = 16
GRID_HEIGHT = 16
SQUARE_SIZE = 50
GRID_SIZE = GRID_WIDTH * GRID_HEIGHT

# Screen
SCREEN_WIDTH = GRID_WIDTH * SQUARE_SIZE
SCREEN_HEIGHT = GRID_HEIGHT * SQUARE_SIZE

# Colors
FONT_COLOR = "#FFFFFF"
BG_COLOR = "#000000"
ALIVE_SNAKE_COLOR = "#00FF00"
DEAD_SNAKE_COLOR = "#960000"
FOOD_COLOR = "#FF0000"

# Game Over
MAX_NO_FOOD_MOVES = GRID_SIZE * 1.5
